guard_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('watch_app.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hood/urls.py
from django.urls import path , include
from hood import views

urlpatterns = [
    path('', views.Home , name="home"),
    path('login/', views.LoginPage , name="login"),
    path('register/', views.Register , name="register"),
    path('logout/', views.LogoutUser , name="logout"),
    path('profile/', views.profile , name="profile"),
    path('profile/update/', views.Update_Profile , name="update_profile"),

    path('business/', views.Businesses , name="business"),#businessroute
    path("alerts/", views.signal , name="alerts"), # alerts


    path('profile/update/<int:pk>', views.edit_user, name='update'),


    path("post/save/", views.create_post, name="save_post"),# save post

    path("business/create/", views.create_business, name="create_business"), # create business
    path("search/", views.search_func , name="search"), # search




    # path("business/create/", views.create_business, name="create_business"), # create business












]

neighbour/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings

from django.conf.urls.static import static 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hood.urls')),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

watch_app/urls.py
from django.urls import path, include

# local imports
from .views import *
from watch_app import views

app_name = 'watch'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/<int:pk>/update/', views.edit_user, name='edit_profile'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('post/', PostView.as_view(), name='post'),
    path('search/', SearchView.as_view(), name='search'),
    # path('facility/', FacilityView.as_view(), name='facility')
]

watch_app/models.py
from django.db.models.signals import post_save
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='user')
    photo = CloudinaryField('profile image', blank=True, null=True)
    location = models.CharField(
        max_length=100, blank=True, null=True, default='')
    bio = models.TextField(blank=True, default='', null=True, max_length=500)
    phone = models.CharField(max_length=20, blank=True, null=True, default='')
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    neighborhood = models.ForeignKey(
        'Neighborhood', on_delete=models.CASCADE, null=True, blank=True)
    street = models.CharField(max_length=80, blank=True, null=True, default='')

    def __str__(self):
        return self.user.username

    def create_profile(sender, **kwargs):
        user = kwargs['instance']
        if kwargs['created']:
            user_profile = UserProfile(user=user)
            user_profile.save()
    post_save.connect(create_profile, sender=User)

    # if user has photo, display it, else display default

    def image_url(self):
        if self.photo and hasattr(self.photo, 'url'):
            return self.photo.url

    def get_absolute_url(self):
        return reverse('profile', kwargs={'pk': self.pk})


# neighborhood model
class Neighborhood(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True, default='')
    location = models.CharField(
        max_length=50, blank=True, null=True, default='')
    occupants = models.IntegerField(blank=True, null=True, default=0)
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='neighborhood', blank=True, null=True)
    facilities = models.ManyToManyField(
        'Facility', blank=True, related_name='neighborhood')
    business = models.ManyToManyField(
        'Business', blank=True, related_name='neighborhood')
    posts = models.ManyToManyField(
        'Post', blank=True, related_name='neighborhood')

    def __str__(self):
        return self.name

    def create_neighborhood(self):
        return self.save()

    def update_neighborhood(self):
        return self.update()

    def delete_neighborhood(self):
        return self.delete()

    def find_neighborhood_by_id(self, id):
        return self.objects.get(id=id)

    def update_occupants(self):
        return self.update()

    def count_occupants(self):
        self.occupants = self.user.userprofile.count()
        return self.occupants


class Facility(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True, default='')
    contact = models.CharField(
        max_length=50, blank=True, null=True, default='')
    email = models.CharField(max_length=80, blank=True, null=True, default='')
    picture = CloudinaryField('Facility image', blank=True, null=True)
    location = models.CharField(
        max_length=50, blank=True, null=True, default='')
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name

    def save_facility(self):
        return self.save()

    def update_facility(self):
        return self.update()

    def delete_facility(self):
        return self.delete()
    
    def find_facility_by_id(self, id):
        return self.objects.get(id=id)

    def search_facility(self, name):
        return Facility.objects.filter(name__icontains=name)


# Businessess model
class Business(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='business')
    name = models.CharField(max_length=100, blank=True, null=True, default='')
    email = models.CharField(max_length=80, blank=True, null=True, default='')
    picture = CloudinaryField('Business image', blank=True, null=True)
    location = models.CharField(
        max_length=50, blank=True, null=True, default='')
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name

    def save_business(self):
        return self.save()

    def update_business(self):
        return self.update()

    def delete_business(self):
        return self.delete()
    
    def find_business_by_id(self, id):
        return self.objects.get(id=id)

    def search_business(self, query):
        return Business.objects.filter(name__icontains=query)


# post created by users
class Post(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='post')
    title = models.CharField(max_length=100, blank=True, null=True, default='')
    body = models.TextField(blank=True, null=True, default='')
    picture = CloudinaryField('Post image', blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.title)

    def save_post(self):
        return self.save()

    def update_post(self):
        return self.update()

    def delete_post(self):
        return self.delete()

    def search_post(self, query):
        posts = Post.objects.filter(body__icontains=query)
        return posts

watch_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

# app imports
from watch_app.models import Post


# user form
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', ]

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name..', }),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name..'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email...'}),
        }


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username',
                  'email', 'password1', 'password2']

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name....', }),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name..'}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username..'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email...'}),
        }


# post form
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'picture']

watch_app/views.py
from django.shortcuts import redirect, render, HttpResponseRedirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.forms.models import inlineformset_factory
from django.core.exceptions import PermissionDenied
from django.views.generic.edit import CreateView
from django.contrib.auth.models import User
from django.contrib import messages
from django.urls import reverse
from django.views import View


# local imports
from .forms import UserForm, CreateUserForm
from .models import Business, Facility, UserProfile, Neighborhood, Post


# Create your views here.
class HomeView(LoginRequiredMixin, View):
    login_url = '/login/'

    def get(self, request):
        try:
            user = request.user
            profile = UserProfile.objects.get(user=user)
            facilities = Facility.objects.filter(
                neighborhood=profile.neighborhood)
            businesses = Business.objects.filter(
                neighborhood=profile.neighborhood)
            posts = Post.objects.all().order_by('-timestamp')[:12]
            context = {
                'title': 'Home',
                'data': profile,
                'facilities': facilities,
                'businesses': businesses,
                'posts': posts
            }
            return render(request, 'watch/index.html', context)
        except UserProfile.DoesNotExist:
            profile = None
            facilities = None
            businesses = None
        return render(request, 'watch/index.html', context)


# user register view
class RegisterView(View):
    """This class view is used to render the register page and execute user registrations."""
    form = CreateUserForm()
    ctx = {
        'title': 'Register',
        'form': form,
    }

    def get(self, request):
        return render(request, 'watch/register.html', self.ctx)

    def post(self, request):
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            form = CreateUserForm()  # reset form
            messages.success(request, 'Registered successfully.')
            return redirect(reverse('watch:login'))
        messages.error(request, 'Registration failed.')
        context = {
            form: form,
        }
        return render(request, 'watch/register.html', context)


class LoginView(View):
    context = {
        'title': 'Login'
    }

    def get(self, request):
        return render(request, 'watch/login.html')

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect(reverse('watch:home'))
        else:
            messages.error(request, 'Invalid username or password.')

        return render(request, 'watch/login.html', self.context)


# logout view
class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect("watch:home")


class ProfileView(LoginRequiredMixin, View):
    login_ur = '/login/'
    """this class view is used to render the profile page and execute user profile updates."""

    def get(self, request):
        user = request.user
        profile = get_object_or_404(UserProfile, user=user)
        posts = Post.objects.filter(user=user).order_by('-timestamp')
        context = {
            'title': 'Profile',
            'user_data': user,
            'profile_data': profile,
            'posts': posts

        }
        return render(request, 'watch/profile.html', context)


@login_required
def edit_user(request, pk):
    user = User.objects.get(pk=pk)

    # prepolate the form with the user's data
    user_form = UserForm(instance=user)

    ProfileInlineFormSet = inlineformset_factory(
        User, UserProfile, fields=('photo', 'bio', 'phone', 'street', 'neighborhood'))
    formset = ProfileInlineFormSet(instance=user)

    if request.user.is_authenticated and request.user.id == user.id:
        if request.method == 'POST':
            user_form = UserForm(
                request.POST, request.FILES, instance=user)
            formset = ProfileInlineFormSet(
                request.POST, request.FILES, instance=user)

            if user_form.is_valid():
                created_user = user_form.save(commit=False)
                formset = ProfileInlineFormSet(
                    request.POST, request.FILES, instance=created_user)
                if formset.is_valid():
                    created_user.save()
                    formset.save()
                    return HttpResponseRedirect('/profile/')

        return render(request, 'watch/edit_profile.html', {
            "pk": pk,
            "user_form": user_form,
            "formset": formset,
        })
    else:
        raise PermissionDenied


# post creation form handler & view
class PostView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'body', 'picture']
    template_name: str = 'watch/post_form.html'
    success_url = '/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        profile = UserProfile.objects.get(user=form.instance.user)
        # hood = get_object_or_404(Neighborhood, name=profile.neighborhood)
        # print('hood: ', hood)
        # hood.posts.set([form.instance])
        return super().form_valid(form)


# search view method
class SearchView(LoginRequiredMixin, View):
    """This class view is used to render the search page and execute search queries."""

    def get(self, request):
        try:
            profile = UserProfile.objects.get(user=request.user)
            if 'search_query' in request.GET and request.GET['search_query']:
                search_term = request.GET.get('search_query')
                search_results = Facility.search_facility('', search_term) or Business.search_business(
                    '', search_term) or Post.search_post('', search_term)
                message = f'Results for {search_term}...'
                ctx = {
                    'facilities': search_results,
                    'message': message,
                    'data': profile
                }
                return render(request, 'watch/index.html', ctx)
        except Facility.DoesNotExist:
            # search_facility = None
            message = 'Err: no results found'
            ctx = {
                'message': message, 'user': request.user}
            return render(request, 'watch/index.html', ctx)

watch_app/templates/watch/edit_profile.html
{% extends 'base.html' %} {% load material_form %} {% block content %}

<div class="col s12 m8 offset-m2">
  <div class="card w-50 p-4 mx-auto">
    <div class="card-content">
      <h2 class="flow-text">Update your Profile</h2>
      <form action="." method="POST" class="padding">
        {% csrf_token %} {{ user_form.as_p }}
        <div class="divider"></div>
        {{ formset.management_form }} {{ formset.as_p }}
        <button type="submit" class="waves-light waves-effect">
          <i class="fas fa-circle-check fa-xl"></i>
        </button>
        <a
          href="#"
          onclick="window.history.back(); return false;"
          title="Cancel"
          class="btn-floating waves-effect waves-light red"
          ><i class="fas fa-history">history</i></a
        >
      </form>
    </div>
  </div>
</div>
{% endblock %}

watch_app/templates/watch/index.html
{% extends 'base.html' %}

<!-- root view -->
{% block content %}
<!-- home content -->
<div class="row">
  <div class="col-md-12">
    <div class="banner rounded mt-5 shadow">
      {% if data.neighborhood %}
      <h3 class="text-center">Welcome to {{data.neighborhood}}</h3>
      {% else %}
      <h3 class="text-center">Hello {{data}}</h3>
      {% endif %}
      <div class="col-md-6 col-sm-10 mx-auto">
        <form action="{% url 'watch:search' %}">
          <div class="input-group mb-2">
            <input
              type="search"
              name="search_query"
              class="form-control col-form-label-lg"
              id="inlineFormInputGroup"
              placeholder="Search..."
              required
            />
            <div class="input-group-append">
              <button class="btn btn-outline-info" type="submit">
                <i class="fas fa-search"></i>
              </button>
            </div>
          </div>
        </form>
        <small class="text-muted"
          >Find: businesses, public facilities, news... around you</small
        >
      </div>
    </div>
    <div class="mini-nav">
      <div class="text-center">
        <a href="#" type="button" class="mini-nav__item nav-btn">Facilities</a>
        <a href="#" type="button" class="mini-nav__item nav-btn"> Posts </a>
        <a href="#" type="button" class="mini-nav__item nav-btn">Businesses</a>
      </div>
    </div>
    <hr />
  </div>
</div>
<!-- home content -->

<div class="container mt-3">
  <h4 class="text-center">{{message}}</h4>
  <div class="news-section d-none">
    <div class="row">
      {% if posts %} {% for post in posts %}
      <div class="col-12 col-lg-4 col-md-6 col-sm-12">
        <div>
          <div class="card mb-2 shadow">
            <div class="card-header">
              <small class="badge-pill bg-primary text-light"
                ><b>{{post.user}}</b></small
              >
              <span class="ml-5">
                <small>{{post.timestamp|timesince}} ago.</small></span
              >
            </div>
            <div class="card-body news-card">
              <h4><strong>{{post}}</strong></h4>

              <p class="post-body">{{post.body|truncatechars:60}}</p>
              <small class="badge-pill bg-secondary">{{data.neighborhood}}</small>
            </div>
          </div>
        </div>
      </div>
      {% endfor %} {% else %}
      <h3 class="text-center">Oops. no news available currently</h3>
      {% endif %}
    </div>
  </div>
  <!--  -->

  <div class="facility-section">
    <div class="row p-2">
      {% if facilities %} {% for facility in facilities %}
      <div class="col-12 col-md-6 col-sm-12 col-lg-4">
        <div class="card facility-card mb-2 shadow-sm">
          <div class="card-body">
            <h3>{{facility.name}}</h3>
            <div class="details">
              <p><i class="fas fa-at"></i> {{ facility.email}}</p>
              <p><i class="fas fa-phone"></i> {{ facility.contact}}</p>
              <p><i class="fas fa-location-pin"></i> {{ facility.location}}</p>
            </div>
          </div>
          <div class="card-footer">
            <small class="badge-pill text-muted"
              >Est. {{facility.created_at|date}}</small
            >
          </div>
        </div>
      </div>
      {% endfor %} {% else %}
      <!-- <h3 class="text-center">Oops. no news available currently</h3> -->
      <p class="text-center">No facilites found in your area.</p>
      {% endif %}
    </div>
  </div>

  <!--  -->
  <div class="business-section d-none">
    <div class="row">
      {% if businesses %} {% for business in businesses %}
      <div class="col-12 col-md-6 col-sm-12 col-lg-4">
        <div class="card mb-2">
          <div class="card-body">
            <h4 class="biz-name">{{business}}</h4>
            <div class="img-d">
              {% load static %}
              <img src="{% static 'media/deliver.gif '%}" alt="" class="w-75" />
            </div>
            <p><i class="fas fa-at"></i> :{{ business.email }}</p>
            <small
              ><i class="fas fa-location-pin"></i>{{business.location}}</small
            >
          </div>
        </div>
      </div>
      {% endfor %} {% else %}
      <p>No businesses found in your area.</p>
      {% endif %}
    </div>
  </div>
</div>

{% load static %}
<!-- content filter code -->
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
  referrerpolicy="no-referrer"
></script>
<script src="{% static 'script.js' %}"></script>
{% endblock %}

watch_app/templates/watch/login.html
{% extends 'base.html' %}
<!-- login template -->
{% block content %}
<!-- login form -->
<div class="wrapper">
  <div class="user-alerts">
    {% for message in messages %}
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      <p>{{ message }}</p>
      <button
        type="button"
        class="close"
        data-dismiss="alert"
        aria-label="Close"
      >
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
  </div>

  <div class="row mt-5 justify-content-center">
    <div class="col-12 col-lg-6 col-md-8 col-sm-12">
      <div class="login-form p-5 rounded shadow-sm">
        {% load static %}
        <div class="text-center">
          <img src="{% static 'media/unlock.png' %}" alt="" height="200px" />
        </div>  
        <form action="" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <input
              type="text"
              placeholder="Username"
              name="username"
              class="form-control"
            />
          </div>
          <div class="form-group input-group">
            <input
              type="password"
              placeholder="Password"
              name="password"
              class="form-control is-valid password-field"
              required
            />
            <div class="input-group-prepend">
              <span class="btn btn-sm show-password input-group-text"
                >show</span
              >
            </div>
          </div>
          <div class="">
            <input
              type="submit"
              class="btn btn-outline-primary btn-sm btn-block is-valid mb-2"
              required
            />
          </div>
        </form>

        <p class="text-muted">
          Don't have an account?
          <a href="{% url 'watch:register' %}">Sign Up</a>
        </p>
      </div>
    </div>
  </div>
</div>

<script>
  // select btn
  const btn = document.querySelector(".show-password");
  btn.addEventListener("click", function () {
    // get input field
    const password = document.querySelector(".password-field");
    if (password.type === "password") {
      // change input type, & show password
      password.type = "text";
      btn.innerHTML = "-";
    } else {
      // change input type, & hide password
      password.type = "password";
      btn.innerHTML = "+";
    }
  });
</script>

{% endblock %}

watch_app/templates/watch/navbar.html
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="{% url 'watch:home' %}"
      ><i class="fab fa-ubuntu fa-xl text-info"></i
      ><span class="logo">N.</span></a
    >
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="mx-auto">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'watch:home' %}"
              >Home <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <!--  -->
        </ul>
      </div>
      <div class="auth-btns m-1">
        {% if user.is_anonymous %}
        <a href="{% url 'watch:login' %}" class="btn btn-outline-info btn-sm">
          Login
        </a>
        <a
          href="{% url 'watch:register' %}"
          class="btn btn-outline-primary me-2 btn-sm"
        >
          Register
        </a>
        {% else %}
        <a
          href="{% url 'watch:logout' %}"
          class="btn btn-outline-secondary btn-sm"
        >
          Logout
        </a>
        <a
          href="{% url 'watch:profile' %}"
          class="m-1 user-icon text-info text-decoration-none"
        >
          <i class="fas fa-user"></i>
          <small class="text-muted">{{request.user}}</small>
        </a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>

watch_app/templates/watch/post_form.html
{% extends 'base.html' %}

<!--  -->
{% block content %}
<div class="row">
  <div class="col-4 mx-auto">
    <div class="card">
      <div class="card-body">
        <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <h3>Create Post</h3>
          <div class="form-group">
            <div class="input-control">
              <label>Title:</label>
              {{form.title}}</div>
          </div>
          <div class="input-group mb-3">
            <p>Content: </p>
            {{form.body}}
          </div>
          <div class="form-group">{{form.picture}}</div>
          <input type="submit" value="post" class="btn btn-primary btn-sm" />
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

watch_app/templates/watch/profile.html
{% extends 'base.html' %}

<!-- user profile -->
{% block content %}
<div class="row profile-banner justify-content-center p-3">
  {% if profile_data %}
  <div class="col col-sm-12 col-md-3 p-2 rounded user-img-section">
    <img
      src="{{ profile_data.image_url|default_if_none:'default.jpg' }}"
      width="50px"
      class="user-img"
    />
  </div>
  <div class="col-12 col-sm-12 col-md-8 p-3 rounded user-details">
    <div>
      <span class="username">
        {{user_data.first_name}} {{user_data.last_name}}
        <small>({{user_data}})</small>
        <!-- username -->
      </span>
      <!-- edit btn -->
      {% if user.id == request.user.id %}
      <a href="{% url 'watch:edit_profile' user.pk %}">
        <i class="fas fa-pen"></i>
      </a>
      {% endif %}
      <span class="ml-4"
        ><a href="{% url 'watch:post' %}"
          ><i class="fas fa-add"></i>post</a
        ></span
      >
    </div>

    <p>{{profile_data.bio}}</p>
    <p class="email"><i class="fas fa-at"></i> {{user_data.email}}</p>
    <div class="profile-details">
      <span class="badge">
        <i class="fas fa-location-pin"></i>
        {{ profile_data.street }}
      </span>
      <span class="badge">
        <i class="fas fa-map-location"></i>
        Neighborhood: {{profile_data.neighborhood}}
      </span>
      <span class="badge">
        <i class="fas fa-phone"></i>
        {{profile_data.phone}}
      </span>
    </div>
  </div>
</div>

<!-- user posts appear -->
<div class="posts-section mt-5">
  <div class="row mt-5">
    {% if posts %} {% for post in posts %}
    <div class="col-12 col-md-6 col-sm-12 col-lg-4">
      <div class="card mb-2">
        <div class="card-body">
          <h4><strong> {{post }}</strong></h4>
          <span class="positon-absolute">
            <i class="fas fa-trash"></i>
          </span>
          <hr />
          <p class="post-body">{{post.body}}</p>
          <small class="badge-pill bg-info text-light"
            >{{post.timestamp|time}}</small
          >
        </div>
      </div>
    </div>
    {% endfor %} {% else %}
    <h4 class="text-center">
      <b> You have no posts yet.</b>
      <a href="{% url 'watch:post' %}">create one.</a>
    </h4>
    {% endif %}
  </div>
</div>
{% endif %} {% endblock %}

watch_app/templates/watch/register.html
{% extends 'base.html' %}

<!-- register form template-->
{% block content %}
<div class="user-alerts">
  {% for message in messages %}
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    <p>{{ message }}</p>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %}
</div>
<!-- regiter form -->
<div class="row mt-4 justify-content-center">
  <div class="col-12 col-lg-6 col-md-8 col-sm-12">
    <div class="register-form p-4 rounded shadow-sm">
      {% load static %}
      <div class="text-center ">
        <img src="{% static 'media/sign.png' %}" alt="" class="sign-img mb-1" height="200px" />
      </div>
      <form action="" method="POST">
        {% csrf_token %}
        <!-- form fields -->
        <div class="form-group">{{ form.first_name }}</div>
        <div class="form-group">{{ form.last_name }}</div>
        <div class="form-group">{{ form.username }}</div>

        <div class="form-group">
          {{ form.email }}
          <small id="emailHelp" class="form-text text-muted"
            >We'll never share your email with anyone else.</small
          >
        </div>

        <div class="form-group">{{ form.password1 }}</div>
        <div class="form-group">{{ form.password2 }}</div>

        <!-- form fields end -->
        <hr />
        <div class="mt-3">
          <input
            class="btn btn-outline-info btn-sm mb-2 btn-block"
            type="submit"
            name="sign-up"
            value="Sign Up"
          />
        </div>
        {{ form.errors }}
        <p class="text-muted">
          Arleady have an account? <a href="{% url 'watch:login' %}">Sign In</a>
        </p>
      </form>
    </div>
  </div>
</div>

<script>
  // get password fields
  const form_fields = document.querySelectorAll("input[type=password]");
  console.log(form_fields);

  // assign placeholders
  form_fields[0].placeholder = "Password..";
  form_fields[1].placeholder = "Confirm Password..";

  // iterate and add bootstrap class
  for (let field in form_fields) {
    form_fields[field].className += "form-control";
  }
</script>
{% endblock %}
<!-- register form template-->